service: CRUD
frameworkVersion: "3"

custom:
  serverless-offline:
    httpPort: 4000
    reloadHandler: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGODB_URI: ${file(env.json):MONGODB_URI}

functions:
  - ${file(routes/note.yml)}

plugins:
  - serverless-offline
